{% set name = "euphonic" %}
{% set version = "1.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/euphonic-{{ version }}.tar.gz
  sha256: 17426b1a0f2ea642444b6da240bb19a2c85166157147e3935d0d7a45a5e594e2

build:
  number: 2
  entry_points:
    - euphonic-dispersion = euphonic.cli.dispersion:main
    - euphonic-dos = euphonic.cli.dos:main
    - euphonic-optimise-dipole-parameter = euphonic.cli.optimise_dipole_parameter:main
    - euphonic-show-sampling = euphonic.cli.show_sampling:main
    - euphonic-intensity-map = euphonic.cli.intensity_map:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - llvm-openmp =15  # [osx]
    - libgomp      # [linux]
  host:
    # Somehow we are ending up with v16 when pin in build: try requirement here as well
    - llvm-openmp =15  # [osx]
    - numpy
    - pip
    - python
  run:
    - importlib_resources >=1.3.0
    - numpy >=1.22
    - packaging
    - pint >=0.19
    - python
    - scipy >=1.10
    - seekpath >=1.1.0
    - spglib >=1.9.4
    - threadpoolctl >=1.0.0

test:
  imports:
    - euphonic
    - euphonic.cli
    - euphonic._euphonic
  commands:
    - pip check
    - euphonic-dispersion --help
    - euphonic-dos --help
    - euphonic-optimise-dipole-parameter --help
    - euphonic-show-sampling --help
    - euphonic-intensity-map --help
  requires:
    - pip
    - matplotlib-base >=3.2.0

about:
  home: https://github.com/pace-neutrons/Euphonic
  summary: Euphonic calculates phonon bandstructures and inelastic neutron scattering intensities from modelling code output (e.g. CASTEP)
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MialLewis
    - DBJochym
    - ajjackson
    - rebeccafair
