{% set name = "euphonic" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/euphonic-{{ version }}.tar.gz
  sha256: 306e2e59f8298c94fac059bd06781dee0438915598b7038384448cd87b0fa849

build:
  number: 0
  entry_points:
    - euphonic-dispersion = euphonic.cli.dispersion:main
    - euphonic-dos = euphonic.cli.dos:main
    - euphonic-optimise-eta = euphonic.cli.optimise_eta:main
    - euphonic-show-sampling = euphonic.cli.show_sampling:main
    - euphonic-intensity-map = euphonic.cli.intensity_map:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - numpy >=1.12.1
    - pip
    - python
  run:
    - importlib_resources >=1.3.0
    - {{ pin_compatible('numpy') }}
    - pint >=0.9
    - python
    - scipy >=1.0.0
    - seekpath >=1.1.0
    - spglib >=1.9.4
    - threadpoolctl >=1.0.0

test:
  imports:
    - euphonic
    - euphonic.cli
    - euphonic._euphonic
  commands:
    - pip check
    - euphonic-dispersion --help
    - euphonic-dos --help
    - euphonic-optimise-eta --help
    - euphonic-show-sampling --help
    - euphonic-intensity-map --help
  requires:
    - pip
    - matplotlib-base >=2.0.0

about:
  home: https://github.com/pace-neutrons/Euphonic
  summary: Euphonic calculates phonon bandstructures and inelastic neutron scattering intensities from modelling code output (e.g. CASTEP)
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ajjackson
    - rebeccafair
