{% set name = "euphonic" %}
{% set version = "1.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/euphonic-{{ version }}.tar.gz
  sha256: 5ba6db5475812fcccb5faa0793d1f14ce9cf56535c303ce0584e4c263ad732a6

build:
  number: 0
  entry_points:
    - euphonic-brille-convergence = euphonic.cli.brille_convergence:main
    - euphonic-dispersion = euphonic.cli.dispersion:main
    - euphonic-dos = euphonic.cli.dos:main
    - euphonic-optimise-dipole-parameter = euphonic.cli.optimise_dipole_parameter:main
    - euphonic-show-sampling = euphonic.cli.show_sampling:main
    - euphonic-intensity-map = euphonic.cli.intensity_map:main
    - euphonic-powder-map = euphonic.cli.powder_map:main
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - llvm-openmp =15  # [osx]
    - libgomp      # [linux]

  host:
    # Somehow we are ending up with v16 when pin in build: try requirement here as well
    - llvm-openmp =15  # [osx]
    - numpy
    - pip
    - python
    - python-build
    - meson-python
    - meson >=1.6
    - packaging
  run:
    - numpy >=1.24
    - packaging
    - pint >=0.22
    - python
    - scipy >=1.10
    - seekpath >=1.1.0
    - spglib >=1.9.4
    - threadpoolctl >=3.0.0
    - toolz >=0.12.1

test:
  imports:
    - euphonic
    - euphonic.cli
    - euphonic._euphonic
  commands:
    - pip check
    - euphonic-dispersion --help
    - euphonic-dos --help
    - euphonic-optimise-dipole-parameter --help
    - euphonic-show-sampling --help
    - euphonic-intensity-map --help
  requires:
    - pip
    - matplotlib-base >=3.8.0

about:
  home: https://github.com/pace-neutrons/Euphonic
  summary: Euphonic calculates phonon bandstructures and inelastic neutron scattering intensities from modelling code output (e.g. CASTEP)
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MialLewis
    - DBJochym
    - ajjackson
    - rebeccafair
